### ISSUE TITLE
Great to see someone practice some leetcode problems

### ISSUE THREAD

**Issue by kevinren1108** [haydenjin/LeetcodeSolutions#1]
I find that practicing data structures and algorithms is really beneficial for software developers. And this is never late to start.
I find you are working on it, that's very awesome and this also reminds me of how I struggled when I first practiced the leetcode problem. I got stuck on the twosum problem for about 15 days. But luckily I find a way to practice leetcode questions and I would like to share it with you. 
So I found some learning materials. Following these materials, I found that there is actually a way to practice leetcode questions. Basically, I would highly recommend practicing by topic type. 
* For example, these relatively basic topics that must be learned: 
Array -> String -> Two pointers -> Linked list -> Binary Search -> Stack and Priority Queue -> Tree -> BFS -> DFS -> Backtracking -> Dynamic Programming. 
* Secondly, There will be some advanced question types:
Matrix -> Topological Sorting -> Graph -> Trie tree.
* And some nice-to-know topics such as Bit manipulate and union-find

And let me know if you want to practice some questions together or if you are interested, we could do some mock tech interviews.

**Comment by haydenjin** [comment]
Thanks for those suggestions Kevin, I appreciate it. I will definitely reach out if I need someone to practice with in the future. Your website looks very nice by the way 👍
